Add winevtlog as another input plugin for logging on windows
newrelic/infrastructure-agent-ansible pull request #178
Opened 2022-04-29 12:55 UTC by danybmx

**DO NOT MERGE**

Hi!

This depends on https://github.com/newrelic/infrastructure-agent/pull/1125

Since fluent-bit 1.9.0 there is a new plugin to get windows logs `winevtlog`. Its output is different than the output from `winlog` so we can't replace one by another but should give the users the option to use the new one.

More information on the infrastructure-agent ticket linked above.

Regards!

https://docs.fluentbit.io/manual/pipeline/inputs/windows-event-log-winevtlog
https://fluentbit.io/announcements/v1.9.0/

2022-05-30 13:56 UTC, rogercoll commented
Hi @danybmx,

The PR https://github.com/newrelic/infrastructure-agent/pull/1125 was included in the infra-agent 1.24.3.

What do you think moving this PR to ready for review?

Thanks,

2022-06-15 17:07 UTC, danybmx commented on templates/newrelic-logging.yml.j2
> +      channel: {{ nrinfragent_logging[log].winevtlog.channel }}
Added it! and also added the elif for winevtlog

2022-06-21 13:51 UTC, rubenruizdegauna commented on templates/newrelic-logging.yml.j2
> +      channel: {{ nrinfragent_logging[log].winevtlog.channel }}
I don't think that you can put an `elif` after the `endif`. 
The `elif` in line 34 and the `endif` in line 35 should not be there.
Feel free to ping me and we can review it together :)

2022-06-21 13:52 UTC, rubenruizdegauna requested changes
https://github.com/newrelic/infrastructure-agent-ansible/pull/178/files#r902649144

2022-07-05 12:10 UTC, rubenruizdegauna approved these changes
LGTM

2022-07-05 12:11 UTC, rubenruizdegauna commented on templates/newrelic-logging.yml.j2
> +      channel: {{ nrinfragent_logging[log].winevtlog.channel }}
no prob :) 
Last commit is not signed. Can you sign it and re-push it please?
Thanks

2022-07-05 12:42 UTC, danybmx commented on templates/newrelic-logging.yml.j2
> +      channel: {{ nrinfragent_logging[log].winevtlog.channel }}
👌🏻

2022-07-06 05:47 UTC, rubenruizdegauna approved these changes

2022-07-11 13:12 UTC, merged